// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class AlbumImage
    {
        public Guid ImgId { get; set; }
        public int AlbumId { get; set; }
        public Guid? UserId { get; set; }
    }
}