// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class Album
    {
        public int AlbumId { get; set; }
        public Guid JobId { get; set; }
        public Guid? UserId { get; set; }
        public string Categoly { get; set; }
        public string Tags { get; set; }
    }
}