// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class AttachFile
    {
        public Guid AttachFileId { get; set; }
        /// <summary>
        /// รหัสอ้างอิงตัวไฟล์
        /// </summary>
        public Guid? RefId { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public double? Size { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public DateTime DeletedDate { get; set; }
        public Guid UpdatedBy { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid DeletedBy { get; set; }
    }
}