// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class ChatMessage
    {
        public Guid? ChatMessageId { get; set; }
        public Guid SenderId { get; set; }
        public Guid RecieverId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ReadDate { get; set; }
        public Guid? ImgId { get; set; }
        public string Message { get; set; }
        public Guid RealSenderId { get; set; }
        public string Ip { get; set; }
    }
}