// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace cisApp.Core
{
    public partial class ChatGroup
    {
        public Guid? ChatGroupId { get; set; }
        public string ChatGroupName { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid UpdatedBy { get; set; }
        public Guid? JobId { get; set; }

        [NotMapped]
        public DateTime? MessageDate { get; set; }
    }
}