// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobPaymentImg
    {
        public Guid? JobPayimgId { get; set; }
        public int? JobPayId { get; set; }
    }
}