// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobPayment
    {
        public int JobPayId { get; set; }
        public Guid? JobId { get; set; }
        public DateTime? PayDate { get; set; }
        /// <summary>
        /// รอชำระเงิน =1 , อยู่ระหว่างตรวจสอบ =2 , สำเร็จ  = 3 , ไม่อนุมัติ/คืนเงิน  = 4 
        /// </summary>
        public int? PayStatus { get; set; }
        public string Comment { get; set; }
    }
}