// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobsCandidate
    {
        public int JobCaId { get; set; }
        public Guid? JobId { get; set; }
        public Guid? UserId { get; set; }
        public int? CaStatusId { get; set; }
    }
}