// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobsTracking
    {
        public int JobTrackingId { get; set; }
        public Guid? JobId { get; set; }
        public DateTime? StatusDate { get; set; }
    }
}