// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobsExamType
    {
        public int JobsExTypeId { get; set; }
        public string Description { get; set; }
    }
}