// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobsLogs
    {
        public int JoblogId { get; set; }
        public Guid JobId { get; set; }
        public string Description { get; set; }
        public string Ipaddress { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}