// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class JobsExamImage
    {
        public Guid JobsExImgId { get; set; }
        public Guid? JobId { get; set; }
        public int? JobsExTypeId { get; set; }
    }
}