// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class Jobs
    {
        public Guid JobId { get; set; }
        /// <summary>
        /// customer
        /// </summary>
        public Guid? UserId { get; set; }
        /// <summary>
        /// รหัสงาน
        /// </summary>
        public string JobNo { get; set; }
        /// <summary>
        /// designer
        /// </summary>
        public Guid? JobCaUserId { get; set; }
        /// <summary>
        /// รหัสประเภทใบงาน
        /// </summary>
        public int? JobTypeId { get; set; }
        /// <summary>
        /// ขอบเขตงาน
        /// </summary>
        public string JobDescription { get; set; }
        /// <summary>
        /// ขนาดพื้นที่ 
        /// </summary>
        public decimal? JobAreaSize { get; set; }
        /// <summary>
        /// ยอดรวม
        /// </summary>
        public decimal? JobPrice { get; set; }
        /// <summary>
        /// ราคา/ตรม
        /// </summary>
        public decimal? JobPricePerSqM { get; set; }
        /// <summary>
        /// สถานะปัจจุบัน
        /// </summary>
        public int? JobStatus { get; set; }
        public DateTime? JobBeginDate { get; set; }
        public DateTime? JobEndDate { get; set; }
    }
}