// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class Menu
    {
        public Guid MenuId { get; set; }
        public Guid? Parent { get; set; }
        public string MenuName { get; set; }
        public string MenuNameEn { get; set; }
        public string MenuUrl { get; set; }
        public bool? IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int? Sequence { get; set; }
        public string Icon { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
    }
}