// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class Otp
    {
        public int OtpId { get; set; }
        /// <summary>
        /// ลงทะเบียนใหม่ จะไม่มี
        /// </summary>
        public Guid? UserId { get; set; }
        public DateTime? CreateDate { get; set; }
        /// <summary>
        /// เวลาหมดอายุ
        /// </summary>
        public DateTime? Expire { get; set; }
        /// <summary>
        /// เลข  otp ที่จัดส่ง
        /// </summary>
        public string OtpMsg { get; set; }
        /// <summary>
        /// กรณี ขอ otp รอบใหม่
        /// </summary>
        public bool? IsReferesh { get; set; }
        /// <summary>
        /// อ้างอิง รหัส otp เดิม กรณี ขอ otp รอบใหม่
        /// </summary>
        public int? OtpRef { get; set; }
        /// <summary>
        /// sms / email
        /// </summary>
        public string OtpType { get; set; }
        /// <summary>
        /// เบอร์โทร / Email
        /// </summary>
        public string SendTo { get; set; }
    }
}