// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using cisApp.library;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace cisApp.Core
{
    public partial class PaymentHistory
    {
        public Guid? PaymentHistoryId { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกดีไซน์เนอร์")]
        public Guid UserId { get; set; }
        [Required(ErrorMessage = "กรุณากรอกจำนวนเงิน")]
        public decimal Amount { get; set; }
        [Required(ErrorMessage = "กรุณาเลือกวันที่จ่ายเงิน")]
        public DateTime? PaymentDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? DeletedDate { get; set; }
        public Guid? DeletedBy { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsPaid { get; set; } = false;
        public string RefCode { get; set; }
        [NotMapped]
        public string PaymentDateStr
        {
            get
            {
                CultureInfo cultureInfo = new CultureInfo("th-TH");
                return (PaymentDate != null) ? PaymentDate.Value.ToString("dd/MM/yyyy", cultureInfo) : "";
            }
            set
            {
                PaymentDate = value.ToDateTimeFormat();
            }
        }
    }
}