// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace cisApp.Core
{
    public partial class Role
    {
        public Guid RoleId { get; set; }
        [Display(Name = "ชื่อกลุ่มสิทธิ์")]
        public string RoleName { get; set; }
        [Display(Name = "สถานะ")]
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public DateTime DeletedDate { get; set; }
        public Guid UpdatedBy { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid DeletedBy { get; set; }
    }
}