// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class RoleMenu
    {
        public Guid RoleMenuId { get; set; }
        public Guid RoleId { get; set; }
        public Guid MenuId { get; set; }
        public int Type { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
    }
}