// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace cisApp.Core
{
    public partial class Settings
    {
        public Guid? SettingId { get; set; }
        public string Keyword { get; set; }
        public string Content { get; set; }
        public DateTime UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string Description { get; set; }
        public bool? IsImg { get; set; }
        public int? OrderBy { get; set; }

        [NotMapped]
        public AttachFile AttachFileImage { get; set; }
        [NotMapped]
        public Guid AttachFileId { get; set; }

        [NotMapped]
        public bool FileRemove { get; set; }

        [NotMapped]
        public string FileBase64 { get; set; }

        [NotMapped]
        public string FileName { get; set; }

        [NotMapped]
        public string FileSize { get; set; }
        [NotMapped]
        public string UrlPath
        {
            get
            {
                if (this.AttachFileImage !=  null)
                {
                    return this.AttachFileImage.UrlPathAPI;
                }
                return "";
            }
        }
        [NotMapped]
        public string FullUrlPath { get; set; }

    }
}