// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class Settings
    {
        public Guid? SettingId { get; set; }
        public string Keyword { get; set; }
        public string Content { get; set; }
        public DateTime UpdatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string Description { get; set; }
    }
}