// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class TmBank
    {
        public int Id { get; set; }
        /// <summary>
        /// รหัสธนาคาร
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// ชื่อธนาคาร
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// ชื่อย่อ
        /// </summary>
        public string NameAbbr { get; set; }
        public bool? IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}