// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class TmSubdistrict
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string NameTh { get; set; }
        public string NameEn { get; set; }
        public int DistrictId { get; set; }
        public int? PostCode { get; set; }
        public bool? IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}