// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class UserImg
    {
        public Guid? UserImgId { get; set; }
        public Guid UserId { get; set; }
    }
}