// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class UserDesignerRequestImage
    {
        public Guid UserDesignerRequestImgId { get; set; }
        public int? UserDesignerRequestId { get; set; }
        public int? UserDesignerRequestImgType { get; set; }
    }
}