// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace cisApp.Core
{
    public partial class UsersResetPassword
    {
        public Guid? UserResetPasswordId { get; set; }
        public Guid UserId { get; set; }
        public string Token { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string RefCode { get; set; }
    }
}